spring:
  config:
    import: optional:file:.env[.properties]
  ai:
    google:
      genai:
        api-key: ${GOOGLE_AI_API_KEY}
        chat:
          model: gemini-3.8-flash
    chat-model: gemini